-- Dealer stock imports and VAT Qualifying flags for Live Source Hub.
-- Live schema was applied directly first, then captured here for source control.

alter table public.live_source_items
  add column if not exists vat_qualifying boolean not null default false,
  add column if not exists vat_qualifying_source text,
  add column if not exists vat_qualifying_verified_at timestamptz,
  add column if not exists dealer_stock_supplier text;

create index if not exists live_source_items_vat_qualifying_live_idx
  on public.live_source_items (connector_id, vat_qualifying, source_status)
  where excluded_from_sourcing=false;

create table if not exists public.dealer_stock_imports (
  id bigint generated by default as identity primary key,
  supplier_name text not null,
  supplier_slug text not null,
  filename text,
  imported_by uuid,
  imported_at timestamptz not null default now(),
  total_rows integer not null default 0,
  vat_qualifying_rows integer not null default 0,
  matched_rows integer not null default 0,
  unmatched_rows integer not null default 0
);

create table if not exists public.dealer_stock_import_rows (
  id bigint generated by default as identity primary key,
  import_id bigint not null references public.dealer_stock_imports(id) on delete cascade,
  supplier_name text not null,
  supplier_slug text not null,
  model_raw text,
  model_clean text,
  mileage integer,
  description_raw text,
  internal_o text,
  registration_date date,
  registration text,
  chassis text,
  vat_code text,
  vat_qualifying boolean not null default false,
  matched_live_source_item_id bigint references public.live_source_items(id) on delete set null,
  match_method text,
  created_at timestamptz not null default now()
);

create index if not exists dealer_stock_import_rows_registration_idx on public.dealer_stock_import_rows (upper(registration));
create index if not exists dealer_stock_import_rows_chassis_idx on public.dealer_stock_import_rows (upper(chassis));
create index if not exists dealer_stock_import_rows_import_id_idx on public.dealer_stock_import_rows (import_id);

alter table public.dealer_stock_imports enable row level security;
alter table public.dealer_stock_import_rows enable row level security;
revoke all on public.dealer_stock_imports from anon, authenticated;
revoke all on public.dealer_stock_import_rows from anon, authenticated;
grant all on public.dealer_stock_imports to service_role;
grant all on public.dealer_stock_import_rows to service_role;

create or replace function public.anybike_clean_dealer_stock_model_v1(p_model text)
returns text
language sql
immutable
set search_path=public,pg_temp
as $$
  select nullif(trim(regexp_replace(regexp_replace(regexp_replace(regexp_replace(
    coalesce(p_model,''),'^\s*\(1\)\s*','','i'),'\*+','','g'),
    '\s*\((?:NO\s*BT|BT|LRH|CRAIG|STATIC\s*DEMO)\)\s*',' ','gi'),
    '\s{2,}',' ','g'))),'')
$$;

create or replace function public.admin_import_dealer_stock_v1(
  p_supplier_name text,p_supplier_slug text,p_filename text,p_rows jsonb
)
returns jsonb
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_import_id bigint; v_row jsonb; v_model_raw text; v_model_clean text; v_reg text;
  v_chassis text; v_vat_code text; v_vq boolean; v_match_id bigint; v_match_method text;
  v_total int:=0; v_vq_count int:=0; v_matched int:=0; v_unmatched int:=0;
  v_unmatched_rows jsonb:='[]'::jsonb;
begin
  if auth.uid() is null or not public.anybike_is_admin() then raise exception 'Admin access required'; end if;
  if nullif(trim(coalesce(p_supplier_name,'')),'') is null then raise exception 'Supplier name is required'; end if;
  if nullif(trim(coalesce(p_supplier_slug,'')),'') is null then raise exception 'Supplier slug is required'; end if;
  if jsonb_typeof(p_rows)<>'array' then raise exception 'Rows must be a JSON array'; end if;

  insert into public.dealer_stock_imports(supplier_name,supplier_slug,filename,imported_by)
  values(trim(p_supplier_name),lower(trim(p_supplier_slug)),nullif(trim(coalesce(p_filename,'')),''),auth.uid())
  returning id into v_import_id;

  for v_row in select value from jsonb_array_elements(p_rows) loop
    v_model_raw:=nullif(trim(coalesce(v_row->>'model','')),'');
    v_model_clean:=public.anybike_clean_dealer_stock_model_v1(v_model_raw);
    v_reg:=nullif(upper(regexp_replace(coalesce(v_row->>'registration',''),'\s+','','g')),'');
    v_chassis:=nullif(upper(trim(coalesce(v_row->>'chassis',''))),'');
    v_vat_code:=upper(trim(coalesce(v_row->>'vat_code','')));
    v_vq:=v_vat_code='VQ'; v_match_id:=null; v_match_method:=null; v_total:=v_total+1;
    if v_vq then v_vq_count:=v_vq_count+1; end if;

    if v_reg is not null then
      select i.id into v_match_id from public.live_source_items i
      where i.connector_id=1 and upper(regexp_replace(coalesce(i.registration,''),'\s+','','g'))=v_reg
      order by (i.source_status='live') desc,i.last_seen_at desc limit 1;
      if v_match_id is not null then v_match_method:='registration'; end if;
    end if;

    if v_match_id is null and v_chassis is not null then
      select i.id into v_match_id from public.live_source_items i
      where i.connector_id=1 and (
        upper(coalesce(i.raw_data->>'chassis',''))=v_chassis or upper(coalesce(i.raw_data->>'vin',''))=v_chassis or
        upper(coalesce(i.specification->>'chassis',''))=v_chassis or upper(coalesce(i.specification->>'vin',''))=v_chassis
      )
      order by (i.source_status='live') desc,i.last_seen_at desc limit 1;
      if v_match_id is not null then v_match_method:='chassis'; end if;
    end if;

    insert into public.dealer_stock_import_rows(
      import_id,supplier_name,supplier_slug,model_raw,model_clean,mileage,description_raw,internal_o,
      registration_date,registration,chassis,vat_code,vat_qualifying,matched_live_source_item_id,match_method
    ) values (
      v_import_id,trim(p_supplier_name),lower(trim(p_supplier_slug)),v_model_raw,v_model_clean,
      case when coalesce(v_row->>'mileage','')~'^\d+$' then (v_row->>'mileage')::int else null end,
      nullif(v_row->>'description',''),nullif(v_row->>'internal_o',''),
      case when coalesce(v_row->>'registration_date','')~'^\d{4}-\d{2}-\d{2}$' then (v_row->>'registration_date')::date else null end,
      v_reg,v_chassis,v_vat_code,v_vq,v_match_id,v_match_method
    );

    if v_match_id is not null then
      update public.live_source_items set
        vat_qualifying=v_vq,
        vat_qualifying_source=trim(p_supplier_name)||' dealer stock import',
        vat_qualifying_verified_at=now(),
        dealer_stock_supplier=trim(p_supplier_name),
        updated_at=now(),
        raw_data=coalesce(raw_data,'{}'::jsonb)||jsonb_build_object('dealer_stock_import',jsonb_build_object(
          'supplier',trim(p_supplier_name),'import_id',v_import_id,'vat_code',v_vat_code,
          'vat_qualifying',v_vq,'model_raw',v_model_raw,'model_clean',v_model_clean,'chassis',v_chassis
        ))
      where id=v_match_id;
      v_matched:=v_matched+1;
    else
      v_unmatched:=v_unmatched+1;
      v_unmatched_rows:=v_unmatched_rows||jsonb_build_array(jsonb_build_object(
        'model',v_model_clean,'registration',v_reg,'chassis',v_chassis,'vat_qualifying',v_vq
      ));
    end if;
  end loop;

  update public.dealer_stock_imports set total_rows=v_total,vat_qualifying_rows=v_vq_count,
    matched_rows=v_matched,unmatched_rows=v_unmatched where id=v_import_id;

  return jsonb_build_object('success',true,'import_id',v_import_id,'total_rows',v_total,
    'vat_qualifying_rows',v_vq_count,'matched_rows',v_matched,'unmatched_rows',v_unmatched,'unmatched',v_unmatched_rows);
end;
$$;
revoke all on function public.admin_import_dealer_stock_v1(text,text,text,jsonb) from public;
grant execute on function public.admin_import_dealer_stock_v1(text,text,text,jsonb) to authenticated;

create or replace function public.admin_get_dealer_stock_imports_v1(p_limit integer default 20)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
begin
  if auth.uid() is null or not public.anybike_is_admin() then raise exception 'Admin access required'; end if;
  return coalesce((select jsonb_agg(to_jsonb(x) order by x.imported_at desc) from (
    select id,supplier_name,supplier_slug,filename,imported_at,total_rows,vat_qualifying_rows,matched_rows,unmatched_rows
    from public.dealer_stock_imports order by imported_at desc limit greatest(1,least(coalesce(p_limit,20),100))
  ) x),'[]'::jsonb);
end;
$$;
revoke all on function public.admin_get_dealer_stock_imports_v1(integer) from public;
grant execute on function public.admin_get_dealer_stock_imports_v1(integer) to authenticated;

create or replace function public.admin_get_live_source_vat_flags_v1(p_item_ids bigint[])
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
begin
  if auth.uid() is null or not public.anybike_is_admin() then raise exception 'Admin access required'; end if;
  return coalesce((select jsonb_agg(jsonb_build_object(
    'id',i.id,'vat_qualifying',i.vat_qualifying,'vat_qualifying_source',i.vat_qualifying_source,
    'dealer_stock_supplier',i.dealer_stock_supplier
  ) order by i.id) from public.live_source_items i where i.id=any(coalesce(p_item_ids,'{}'::bigint[]))),'[]'::jsonb);
end;
$$;
revoke all on function public.admin_get_live_source_vat_flags_v1(bigint[]) from public;
grant execute on function public.admin_get_live_source_vat_flags_v1(bigint[]) to authenticated;
