-- Private admin-only international shippers and destination ports directory.
create table if not exists public.international_ports (
  id bigint generated by default as identity primary key,
  country text not null,
  port_name text not null,
  city_region text,
  notes text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists international_ports_country_name_uq
  on public.international_ports (lower(country), lower(port_name));

create table if not exists public.international_shippers (
  id bigint generated by default as identity primary key,
  company_name text not null,
  base_country text,
  city text,
  contact_name text,
  email text,
  phone text,
  website text,
  countries_served jsonb not null default '[]'::jsonb,
  ports_served jsonb not null default '[]'::jsonb,
  services jsonb not null default '[]'::jsonb,
  notes text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists international_shippers_company_uq
  on public.international_shippers (lower(company_name));

alter table public.international_ports enable row level security;
alter table public.international_shippers enable row level security;

revoke all on table public.international_ports from anon, authenticated;
revoke all on table public.international_shippers from anon, authenticated;

create or replace function public.admin_get_international_ports_v1()
returns setof public.international_ports
language plpgsql
security definer
set search_path=''
as $function$
begin
  if not public.anybike_is_admin() then raise exception 'Admin access required'; end if;
  return query select * from public.international_ports order by country,port_name;
end;
$function$;

create or replace function public.admin_save_international_port_v1(
  p_id bigint,
  p_country text,
  p_port_name text,
  p_city_region text default null,
  p_notes text default null,
  p_is_active boolean default true
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare v_id bigint;
begin
  if not public.anybike_is_admin() then raise exception 'Admin access required'; end if;
  if nullif(trim(coalesce(p_country,'')),'') is null then raise exception 'Country is required'; end if;
  if nullif(trim(coalesce(p_port_name,'')),'') is null then raise exception 'Port name is required'; end if;

  if p_id is null then
    insert into public.international_ports(country,port_name,city_region,notes,is_active,created_at,updated_at)
    values(trim(p_country),trim(p_port_name),nullif(trim(coalesce(p_city_region,'')),''),nullif(trim(coalesce(p_notes,'')),''),coalesce(p_is_active,true),now(),now())
    returning id into v_id;
  else
    update public.international_ports
    set country=trim(p_country),
        port_name=trim(p_port_name),
        city_region=nullif(trim(coalesce(p_city_region,'')),''),
        notes=nullif(trim(coalesce(p_notes,'')),''),
        is_active=coalesce(p_is_active,true),
        updated_at=now()
    where id=p_id
    returning id into v_id;
    if v_id is null then raise exception 'Port not found'; end if;
  end if;

  return jsonb_build_object('success',true,'id',v_id);
end;
$function$;

create or replace function public.admin_get_international_shippers_v1()
returns setof public.international_shippers
language plpgsql
security definer
set search_path=''
as $function$
begin
  if not public.anybike_is_admin() then raise exception 'Admin access required'; end if;
  return query select * from public.international_shippers order by company_name;
end;
$function$;

create or replace function public.admin_save_international_shipper_v1(
  p_id bigint,
  p_company_name text,
  p_base_country text default null,
  p_city text default null,
  p_contact_name text default null,
  p_email text default null,
  p_phone text default null,
  p_website text default null,
  p_countries_served jsonb default '[]'::jsonb,
  p_ports_served jsonb default '[]'::jsonb,
  p_services jsonb default '[]'::jsonb,
  p_notes text default null,
  p_is_active boolean default true
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $function$
declare v_id bigint;
begin
  if not public.anybike_is_admin() then raise exception 'Admin access required'; end if;
  if nullif(trim(coalesce(p_company_name,'')),'') is null then raise exception 'Company name is required'; end if;

  if p_id is null then
    insert into public.international_shippers(
      company_name,base_country,city,contact_name,email,phone,website,
      countries_served,ports_served,services,notes,is_active,created_at,updated_at
    )
    values(
      trim(p_company_name),nullif(trim(coalesce(p_base_country,'')),''),nullif(trim(coalesce(p_city,'')),''),
      nullif(trim(coalesce(p_contact_name,'')),''),nullif(trim(coalesce(p_email,'')),''),nullif(trim(coalesce(p_phone,'')),''),
      nullif(trim(coalesce(p_website,'')),''),coalesce(p_countries_served,'[]'::jsonb),coalesce(p_ports_served,'[]'::jsonb),
      coalesce(p_services,'[]'::jsonb),nullif(trim(coalesce(p_notes,'')),''),coalesce(p_is_active,true),now(),now()
    ) returning id into v_id;
  else
    update public.international_shippers
    set company_name=trim(p_company_name),
        base_country=nullif(trim(coalesce(p_base_country,'')),''),
        city=nullif(trim(coalesce(p_city,'')),''),
        contact_name=nullif(trim(coalesce(p_contact_name,'')),''),
        email=nullif(trim(coalesce(p_email,'')),''),
        phone=nullif(trim(coalesce(p_phone,'')),''),
        website=nullif(trim(coalesce(p_website,'')),''),
        countries_served=coalesce(p_countries_served,'[]'::jsonb),
        ports_served=coalesce(p_ports_served,'[]'::jsonb),
        services=coalesce(p_services,'[]'::jsonb),
        notes=nullif(trim(coalesce(p_notes,'')),''),
        is_active=coalesce(p_is_active,true),
        updated_at=now()
    where id=p_id
    returning id into v_id;
    if v_id is null then raise exception 'Shipper not found'; end if;
  end if;

  return jsonb_build_object('success',true,'id',v_id);
end;
$function$;

revoke all on function public.admin_get_international_ports_v1() from public,anon;
revoke all on function public.admin_save_international_port_v1(bigint,text,text,text,text,boolean) from public,anon;
revoke all on function public.admin_get_international_shippers_v1() from public,anon;
revoke all on function public.admin_save_international_shipper_v1(bigint,text,text,text,text,text,text,text,jsonb,jsonb,jsonb,text,boolean) from public,anon;

grant execute on function public.admin_get_international_ports_v1() to authenticated;
grant execute on function public.admin_save_international_port_v1(bigint,text,text,text,text,boolean) to authenticated;
grant execute on function public.admin_get_international_shippers_v1() to authenticated;
grant execute on function public.admin_save_international_shipper_v1(bigint,text,text,text,text,text,text,text,jsonb,jsonb,jsonb,text,boolean) to authenticated;
